/**
 * @file main.cpp
 * @author Jack Schumacher (jackrschumacher@gmail.com)
 *
 */
#include <Arduino.h>
#include <ESP32Servo.h>
#include <Adafruit_NeoPixel.h>
#include "LittleFS.h"
// #include <ASTRARevCAN.h>

// Remove to disable the boards inbuilt LED blinking
#define BLINK

bool ledState = false;
// Servo Pins (generated by Gemini): 13,14,18,19,22,23,25,26,27


  // Defined servos (3 for valves, 3 for distributors, 3 for chemicals)
  Servo valve1, valve2, valve3, distributor1, distributor2, distributor3, chemical1, chemical2, chemical3;




void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200); // May need to change this later

  

    // Valves are on top of the unit
  valve1.attach(13);
  valve2.attach(14);
  valve3.attach(18);

  // Distributors are on each of the peices that hang down
  distributor1.attach(19);
  distributor2.attach(22);
  distributor3.attach(23);

  // Chemical servos are in the back of the unit (the larger servos)
  chemical1.attach(25);
  chemical2.attach(26);
  chemical3.attach(27);


}

void loop() {
  // put your main code here, to run repeatedly:
  readSerialCommand();

}

void readSerialCommand(){
  const int BUFFER_SIZE = 32;
  static char command_buffer[BUFFER_SIZE+1];
  static int length = 0;

  while(Serial.available()){
    char current_value = Serial.read();
    int seperatorIndex = input.indexOf(':');

    
    if((current_value == '\r') || (current_value == '\n')){

      if(length > 0){
        command_buffer[length] = '\0';
        processSerialCommand(command_buffer);
        length = 0;
      }
    }
    else if(length < BUFFER_SIZE){
        command_buffer[length++] = current_value;
        command_buffer[length] = '\0';
      
      }
    
  }
}

void processSerialCommand(char* command_buffer){
  String command = String(command_buffer);
  command.trim();

  if (seperatorIndex != -1){
      String command  = input.substring(0,seperatorIndex);
      String angleString = input.substring(seperatorIndex +1);
      int angle = valueStr.toInt();
      if((angle >= 0) && (angle <= 180)){
        if (command == "v1"){
        valve1.write(angle);
      }
      }
      
    }
  




  else{
      if(command == "ping"){
      Serial.println("pong");

    }
    else if(command == "time"){ //Print board elapsed time in milliseconds
      Serial.print("Current time (ms):");
      Serial.println(millis());
    }
    //  else if(command == "led"){ //Turn on the board's internal LED - Holdover from last year and may be modified
    //           digitalWrite(LED_BUILTIN, !ledState);
    //           ledState = !ledState;
    // }
    else if(command == "system"){ //See system ram usage
      uint32_t freeHeap = ESP.getFreeHeap();
      uint32_t totalHeap = ESP.getHeapSize();
      uint32_t usedHeap = totalHeap - freeHeap;
      float ramUsage = (float)usedHeap / totalHeap *100.0;
      Serial.printf("RAM Usage:    %d / %d bytes (%.1f%%)\n", usedHeap, totalHeap, ramUsage);
    }
  }
  
}
  



