; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32devkit-v1]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps = 
	https://github.com/SHC-ASTRA/rover-Embedded-Lib
	https://github.com/madhephaestus/ESP32Servo.git
	handmade0octopus/ESP32-TWAI-CAN@^1.0.1
	adafruit/Adafruit PWM Servo Driver Library@^3.0.3
monitor_filters = send_on_enter
build_flags = 
	-D CITADEL
board = esp32-s3-devkitc-1
